version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=curso_sequelize
      - POSTGRES_USER=chiuauau
      - POSTGRES_PASSWORD=2771az